### ISSUE TITLE
ESM Loader Issue on Windows

### ISSUE THREAD

**Issue by Frasob** [tobiasdiez/nuxt-graphql-server#28]
I install your package like you wrote at your instruction.

Unfortunaly after I start my nuxt, I got the following error:

>  [worker reload] [worker init] Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'6:21 

 
 It seems the virtual modules for schema and/or resolvers cause this error and only on windows machines.

May be you can have a look at this problem, Many Thanks :)

**Comment by tobiasdiez** [comment]
I use the module without any issues on windows. Would you mind sharing a reproduction repo?

**Comment by tobiasdiez** [comment]
I could now reproduce it, and also fix it by upgrading to the latest nuxt version. I've now also added ci for windows to verify that everything is working fine. Thus closing now.

**Comment by tobiasdiez** [comment]
Oh, I can still reproduce this in dev mode. I think it's an issue upstream and I've opened https://github.com/nuxt/nuxt/issues/19453.

**Comment by tobiasdiez** [comment]
Use this as workaround: https://github.com/dword-design/nuxt-mail/pull/174/files
