### ISSUE TITLE
Module import error

### ISSUE THREAD

**Issue by heindetotverre** [tobiasdiez/nuxt-graphql-server#34]
Hi I've added your module and I'm running in an error importing some module. 

Just made a base nuxt 3 project, and then added your module as per instructions.

My package.json:
```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "nuxt": "^3.1.2"
  },
  "dependencies": {
    "@apollo/server": "^4.3.3",
    "@as-integrations/h3": "^1.1.5",
    "graphql": "^16.6.0",
    "nuxt-graphql-server": "^1.1.6"
  }
}
```

During prepare and runtime I run into the following error after adding the module in nuxt.config.ts:

` ERROR  Error while requiring module nuxt-graphql-server: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/runner/work/nuxt-graphql-server/nuxt-graphql-server/node_modules/.pnpm/jiti@1.16.0/node_modules/jiti/lib/index.js' imported from /Users/matthiaspoortvliet/CODE/test/node_modules/nuxt-graphql-server/dist/module.mjs
`

**Comment by k10wl** [comment]
Same issue here
Seems like v1.16.0 is broken. Rolling back to v1.15.0 helped @heindetotverre

![image](https://user-images.githubusercontent.com/72667957/220617569-487ff068-4837-44b8-8db9-46200b8b7120.png)

**Comment by tobiasdiez** [comment]
Sorry for the late reply. There was indeed an error in the deployment pipeline, which is now fixed. Version 1.2 should work now as expected.

**Comment by heindetotverre** [comment]
Ah I used your h3 package and made my own implementation but thanks!
