### ISSUE TITLE
Type declarations for virtual modules cannot be found

### ISSUE THREAD

**Issue by corydeppen** [tobiasdiez/nuxt-graphql-server#71]
I've installed nuxt-graphql-server (2.0.1) into a new Nuxt (3.7.1) project and I'm seeing a TS error `Cannot find module '#graphql/resolver' or its corresponding type declarations` in the `api/graphql.ts` file I added. This appears to be related to the error `Non-relative paths are not allowed when 'baseUrl' is not set` I'm seeing in the root `tsconfig.json` file. I confirmed that the generated file in the `.nuxt` directory doesn't have a `baseUrl` option defined.

```json
"#graphql/schema": [
  ".nuxt/types/graphql-server.d.ts"
],
"#graphql/resolver": [
  ".nuxt/types/graphql-server-resolver.d.ts"
],
```

I believe this may be due to a [recent change in Nuxt 3.7.0](https://github.com/nuxt/nuxt/releases/tag/v3.7.0):

> We now use purely relative paths in the generated `tsconfig.json` instead of setting a `baseUrl`.

**Comment by tobiasdiez** [comment]
Let's hope this is fixed with https://github.com/tobiasdiez/nuxt-graphql-server/pull/68.

**Comment by awdr74100** [comment]
@tobiasdiez macos also has the same problem.

**Comment by tobiasdiez** [comment]
Fixed by https://github.com/tobiasdiez/nuxt-graphql-server/pull/68.
