### ISSUE TITLE
Cannot find module '#graphql/schema' or its corresponding type declarations

### ISSUE THREAD

**Issue by awdr74100** [tobiasdiez/nuxt-graphql-server#74]
Many thanks to @tobiasdiez and @sduduzog for their contributions to this module! especially this #68

But there may still be some problems:
![螢幕擷取畫面 2023-09-16 012940](https://github.com/tobiasdiez/nuxt-graphql-server/assets/47501692/e45a0b6d-07f8-4a02-a812-0c31dc42d8ec)
![螢幕擷取畫面 2023-09-16 013004](https://github.com/tobiasdiez/nuxt-graphql-server/assets/47501692/6fb0d6e9-fdcb-4606-b80f-a1e37e3e7a39)

`#graphql/resolver` does not have this problem and can be correctly identified.

Is it possible that vscode cannot correctly identify the path to the `.mjs` file?

**Comment by sduduzog** [comment]
I'll look into this. I'll create a stackblitz repository to try and reproduce

**Comment by tobiasdiez** [comment]
I can reproduce the issue, but couldn't find a solution yet. Simply correcting the path in nuxt's `tsconfig.json` doesn't seem to work.

**Comment by sduduzog** [comment]
I've been failing to create a stackblitz repo for this so I haven't been able to do anything.

But this should only affect types and not the functionality?? I'll try again with a fresh project locally tonight

**Comment by sduduzog** [comment]
As a work around @awdr74100 

Please create a declaration file anywhere in your project, e.g. `temp.d.ts`

and add the following
```typescript
declare module '#graphql/schema' {
  export const schema: string
}
```

**Comment by awdr74100** [comment]
@sduduzog thank you for your help!
